services:
  hugin-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hugin-ui
    ports:
      - "8096:80"
    restart: always
    depends_on:
      - fantasmometro-api

  fantasmometro-api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: fantasmometro-api
    restart: always
